# Generated by Django 2.0 on 2017-12-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parkinginfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('areaid', models.CharField(max_length=50)),
                ('areaName', models.CharField(max_length=50)),
                ('parkName', models.CharField(max_length=50)),
                ('totalSpace', models.IntegerField()),
                ('surplusSpace', models.IntegerField()),
                ('payGuide', models.TextField()),
                ('introduction', models.TextField()),
                ('address', models.TextField()),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('parkId', models.CharField(max_length=50)),
                ('update_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'parkinginfo',
            },
        ),
    ]
